- hosts: servers
  become: yes
  vars:
      mysql_root_password: '{{ mysql_root_password }}'
  tasks:
      - package:
            name:
                - python3-mysqldb
                - mysql-server
            state: present
      - service:
            name: mysql
            state: started
            enabled: yes
      - mysql_db:
            name:
                - wordpress
            state: present
            login_user: root
            login_password: '{{ mysql_root_password }}'
