---
- hosts: servers
  become: true
  tasks:
      - npm:
            name: ghost-cli
            global: yes
            state: present
      - user:
            name: ghost
            state: present
      - file:
            path: /var/www/ghost
            state: directory
            owner: ghost
            group: ghost
