---
- hosts: servers
  become: true
  tasks:
      - apt:
            upgrade: yes
            update_cache: yes
      - package:
            name:
                - curl
                - python3-pip
                - libpq-dev
                - postgresql
            state: present
      - apt_key:
            url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
            state: present
      - apt_repository:
            repo: 'deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main'
            state: present
            update_cache: yes
      - package:
            name: nodejs
            state: present
