- hosts: servers
  become: yes
  tasks:
      - docker_container:
            name: wordpress
            image: wordpress:latest
            restart_policy: always
            state: started
            ports:
                - '8080:80'
            volumes:
                - wordpress:/var/www/html
            env:
                WORDPRESS_DB_HOST: db
                WORDPRESS_DB_USER: '{{ db_user }}'
                WORDPRESS_DB_PASSWORD: '{{ db_password }}'
                WORDPRESS_DB_NAME: wordpress
            links:
                - db
