name: Release
on:
  push:
    tags:
      - '*'
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - id: dash_tag
        run: echo ::set-output name=TAG::${TAG//./-}
        env:
          TAG: ${{ steps.get_tag.outputs.TAG }}
    outputs:
      TAG: ${{ steps.get_tag.outputs.TAG }}
      DASH_TAG: ${{ steps.dash_tag.outputs.TAG }}
  worker:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - run: sed -i 's/com\./com-${{ needs.prepare.outputs.DASH_TAG }}\./' wrangler.toml
      - run: npm ci
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
